import './globals.css'
import { Inter } from 'next/font/google'
import createCache from '@emotion/cache';

const inter = Inter({ subsets: ['latin'] })

function createEmotionCache() {
  return createCache({ key: "css", prepend: true });
 }

export const metadata = {
  title: 'Andrew Ohakam',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
        <html lang="en">
          <head>
            <link rel="preconnect" href="https://fonts.googleapis.com"></link>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
            <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet"></link>
          </head>
          <body className={inter.className}>{children}</body>
        </html>
  )
}
